# Generated by Django 3.2.4 on 2021-10-02 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bn', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=800)),
                ('newsdes', models.TextField(max_length=8000)),
                ('newspic', models.ImageField(default='', upload_to='static/news')),
                ('ndate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cpick', models.ImageField(default='', upload_to='static/category/')),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='hnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spick', models.ImageField(default='', upload_to='static/category/')),
                ('sheadlines', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=800)),
                ('newsdes', models.TextField(max_length=8000)),
                ('ndate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=80, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=20)),
                ('ppick', models.ImageField(default='', upload_to='static/profile/')),
                ('address', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='', upload_to='static/videos/')),
                ('vheadlines', models.CharField(max_length=400)),
                ('vlink', models.URLField(default='')),
                ('vdate', models.DateField()),
                ('city', models.CharField(max_length=200)),
                ('vcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.CreateModel(
            name='tsnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tspick', models.ImageField(default='', upload_to='static/news/')),
                ('tsheadlines', models.CharField(max_length=400)),
                ('subject', models.CharField(max_length=800)),
                ('newsdes', models.TextField(max_length=8000)),
                ('city', models.CharField(max_length=200)),
                ('ndate', models.DateField()),
                ('ncategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.CreateModel(
            name='trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ft', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=800)),
                ('newsdes', models.TextField(max_length=8000)),
                ('newspic', models.ImageField(default='', upload_to='static/news')),
                ('ndate', models.DateField()),
                ('ncategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.CreateModel(
            name='tnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnpick', models.ImageField(default='', upload_to='static/news/')),
                ('tnheadlines', models.CharField(max_length=400)),
                ('subject', models.CharField(max_length=800)),
                ('newsdes', models.TextField(max_length=8000)),
                ('city', models.CharField(max_length=200)),
                ('ndate', models.DateField()),
                ('ncategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('headlines', models.CharField(max_length=400)),
                ('subject', models.CharField(max_length=800)),
                ('newsdes', models.TextField(max_length=8000)),
                ('newspic', models.ImageField(default='', upload_to='static/news')),
                ('ndate', models.DateField()),
                ('ncategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.CreateModel(
            name='newcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpick', models.ImageField(default='', upload_to='static/category/')),
                ('fcity', models.CharField(max_length=200)),
                ('fsubject', models.CharField(max_length=800)),
                ('fnewsdes', models.TextField(max_length=8000)),
                ('fdate', models.DateField()),
                ('fheadlines', models.CharField(max_length=400)),
                ('sheadlines', models.CharField(max_length=400)),
                ('scity', models.CharField(max_length=200)),
                ('ssubject', models.CharField(max_length=800)),
                ('snewsdes', models.TextField(max_length=8000)),
                ('snewspic', models.ImageField(default='', upload_to='static/news')),
                ('sdate', models.DateField()),
                ('theadlines', models.CharField(max_length=400)),
                ('tcity', models.CharField(max_length=200)),
                ('tsubject', models.CharField(max_length=800)),
                ('tnewsdes', models.TextField(max_length=8000)),
                ('tnewspic', models.ImageField(default='', upload_to='static/news')),
                ('tdate', models.DateField()),
                ('foheadlines', models.CharField(max_length=400)),
                ('focity', models.CharField(max_length=200)),
                ('fosubject', models.CharField(max_length=800)),
                ('fonewsdes', models.TextField(max_length=8000)),
                ('fonewspic', models.ImageField(default='', upload_to='static/news')),
                ('fodate', models.DateField()),
                ('fiheadlines', models.CharField(max_length=400)),
                ('ficity', models.CharField(max_length=200)),
                ('fisubject', models.CharField(max_length=800)),
                ('finewsdes', models.TextField(max_length=8000)),
                ('finewspic', models.ImageField(default='', upload_to='static/news')),
                ('fidate', models.DateField()),
                ('ncategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
    ]
