# Generated by Django 3.2.4 on 2021-10-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndes', models.TextField(max_length=5000)),
                ('ndate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='videos',
            name='video',
        ),
        migrations.AddField(
            model_name='videos',
            name='thumb',
            field=models.ImageField(default='', upload_to='static/thumbnail/'),
        ),
        migrations.AddField(
            model_name='videos',
            name='vdes',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='videos',
            name='vdate',
            field=models.DateField(default=''),
        ),
    ]
