# Generated by Django 3.2.4 on 2021-10-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211002_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
    ]
